services:
  web:
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle:/bundle
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - HISTFILE=/app/log/.bash_history 
    
  sidekiq: 
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    build: .
    command: 'sidekiq -C config/sidekiq.yml.erb'
    volumes:
      - .:/app
      - bundle:/bundle
    env_file:
      - .env
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres
      interval: 2s
      timeout: 5s
      retries: 30
  redis:
    image: redis:7.0
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
  cable:
    depends_on:
      - 'redis'
    build: .
    command: puma -p 28080 cable/config.ru
    ports:
      - '28080:28080'
    volumes:
      - '.:/app'
    env_file:
      - '.env'
volumes:
  pg_data:
  redis_data:
  bundle: