development:
  adapter: redis
  url: redis://redis:6379/2

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: yt_sharing_production
