# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

user  = User.create(email: "user@gmail.com",  password: "123123123", password_confirmation: "123123123")
user2 = User.create(email: "user2@gmail.com", password: "123123123", password_confirmation: "123123123")

link  = Link.create(sharer_id: user.id,   title: "Người Được Chọn - B Ray x Huỳnh Công Hiếu x 24k.Right | Rap Việt 2023 [MV Lyrics]", description: "Người Được Chọn - B Ray x Huỳnh Công Hiếu x 24k.Right | Rap Việt 2023 [MV Lyrics]\n\n#RapViệtMùa3 #RapVietSeason3 #VieChannel #VieGiảiTrí #VieON #DatVietVAC\n\n👉 Xem sớm nhất trên ứng dụng VieON: https://click.vieon.vn/wSBG/ytrvm3\n\n▶ Tìm nghe các bản audio của Tập 16 Rap Việt Mùa 3 tại đây: https://wmvn.lnk.to/RVS3-EP16\n▶ Follow playlist Rap Việt Mùa 3 để nghe toàn bộ các bản thu từ Rap Việt: https://wmvn.lnk.to/RAPVIET-MUA3\n\nĐón xem #RapViệtMùa3 sắp phát sóng trên kênh truyền hình Vie Channel - HTV2, Vie GIẢITRÍ và ứng dụng VieON\n\nRap Việt được mua bản quyền từ chương trình đình đám tại Thái Lan – The Rapper, đây là format từng đạt nhiều giải thưởng vang dội như Giải thưởng truyền hình châu Á lần thứ 23 – 2018 với hạng mục Chương trình giải trí tổng hợp hay nhất, Giải thưởng sáng tạo của Viện hàn lâm châu Á 2019, Giải thưởng Zocial Awards Thái Lan 2019 - Giải thưởng giải trí hay nhất trên mạng xã hội.\n\nRap Việt Mùa 3 đang phát sóng, những thí sinh xuất sắc được tuyển chọn khắp Việt Nam sẽ quy tụ tại sân khấu Rap Việt Mùa 3 để tranh tài nhằm tìm ra người nắm giữ ngôi vị cao nhất mùa thứ 3. \n\nĐăng ký hội viên ngay nào👇:\nhttps://www.youtube.com/channel/UCkna2OcuN1E6u5I8GVtdkOw/join\n\n★ Mọi nhu cầu quảng cáo và tài trợ xin liên hệ: Công Ty Cổ Phần Vie Channel\n► Hotline: 0907.950.371 (Mr. Đức Khoa)\n► Email: khoa.nguyen@viechannel.vn hoặc sales@viechannel.vn\n\n📣 Đừng quên subscribe để xem thật nhiều phim mới nhé! \n🎈 Subscribe ngay: http://bit.ly/VieChannelHTV2\n\nTải app VieON tại: https://click.vieon.vn/wSBG/ytapp\n\nXem các chương trình hấp dẫn khác của Vie Channel:\n►Rap Việt Full: https://bit.ly/RAPVIETSS3\n►Người Ấy Là Ai Full: https://bit.ly/NALASS5\n►Hoa Vương Full: https://bit.ly/HoaVươngFull\n►The Masked Singer Vietnam Full: https://bit.ly/TheMaskedSingerSS1\n\nHoặc xem thêm trên hệ thống Vie Channel:\n►Website: http://viechannel.vn/\n►Fanpage: https://www.facebook.com/VieChannelHTV2/\n►Instagram: https://www.instagram.com/viechannelhtv2/", url: "https://www.youtube.com/watch?v=nIfcHxJbW5I")
link2 = Link.create(sharer_id: user2.id,  title: "Truy Lùng Bảo Vật - 24k.Right ft. Sofia - Team B Ray | Rap Việt 2023 [MV Lyrics]",  description: "Truy Lùng Bảo Vật - 24k.Right ft. Sofia - Team B Ray | Rap Việt 2023 [MV Lyrics]\n\n#RapViệtMùa3 #RapVietSeason3 #VieChannel #VieGiảiTrí #VieON #DatVietVAC\n\n👉 Xem sớm nhất trên ứng dụng VieON: https://click.vieon.vn/wSBG/ytrvm3\n\n▶ Tìm nghe các bản audio của Tập 15 Rap Việt Mùa 3 tại đây: https://wmvn.lnk.to/RVS3-EP15\n▶ Follow playlist Rap Việt Mùa 3 để được cập nhật sớm nhất khi audio được phát hành: https://wmvn.lnk.to/RAPVIET-MUA3\n\nĐón xem #RapViệtMùa3 sắp phát sóng trên kênh truyền hình Vie Channel - HTV2, Vie GIẢITRÍ và ứng dụng VieON\n\nRap Việt được mua bản quyền từ chương trình đình đám tại Thái Lan – The Rapper, đây là format từng đạt nhiều giải thưởng vang dội như Giải thưởng truyền hình châu Á lần thứ 23 – 2018 với hạng mục Chương trình giải trí tổng hợp hay nhất, Giải thưởng sáng tạo của Viện hàn lâm châu Á 2019, Giải thưởng Zocial Awards Thái Lan 2019 - Giải thưởng giải trí hay nhất trên mạng xã hội.\n\nRap Việt Mùa 3 đang phát sóng, những thí sinh xuất sắc được tuyển chọn khắp Việt Nam sẽ quy tụ tại sân khấu Rap Việt Mùa 3 để tranh tài nhằm tìm ra người nắm giữ ngôi vị cao nhất mùa thứ 3. \n\nĐăng ký hội viên ngay nào👇:\nhttps://www.youtube.com/channel/UCkna2OcuN1E6u5I8GVtdkOw/join\n\n★ Mọi nhu cầu quảng cáo và tài trợ xin liên hệ: Công Ty Cổ Phần Vie Channel\n► Hotline: 0907.950.371 (Mr. Đức Khoa)\n► Email: khoa.nguyen@viechannel.vn hoặc sales@viechannel.vn\n\n📣 Đừng quên subscribe để xem thật nhiều phim mới nhé! \n🎈 Subscribe ngay: http://bit.ly/VieChannelHTV2\n\nTải app VieON tại: https://click.vieon.vn/wSBG/ytapp\n\nXem các chương trình hấp dẫn khác của Vie Channel:\n►Rap Việt Full: https://bit.ly/RAPVIETSS3\n►Người Ấy Là Ai Full: https://bit.ly/NALASS5\n►Hoa Vương Full: https://bit.ly/HoaVươngFull\n►The Masked Singer Vietnam Full: https://bit.ly/TheMaskedSingerSS1\n\nHoặc xem thêm trên hệ thống Vie Channel:\n►Website: http://viechannel.vn/\n►Fanpage: https://www.facebook.com/VieChannelHTV2/\n►Instagram: https://www.instagram.com/viechannelhtv2/", url: "https://www.youtube.com/watch?v=c5XLdnN11ks")
